name: Publish to BCR

on:
  # Manually trigger the publish workflow
  workflow_dispatch:
    inputs:
      tag_name:
        description: Release tag to publish to the Bazel Central Registry
        required: true
        type: string

jobs:
  publish:
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v2
    with:
      tag_name: ${{ inputs.tag_name }}
      # Set to false since not using the release_ruleset workflow
      attest: false
    permissions:
      contents: write
    secrets:
      publish_token: ${{ secrets.BCR_PUBLISH_TOKEN }}
