name: Publish to BCR

on:
  # Manually trigger the publish workflow
  workflow_dispatch:
    inputs:
      tag_name:
        description: Release tag to publish to the Bazel Central Registry
        required: true
        type: string

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag_name }}

      - name: Publish to BCR
        uses: bazel-contrib/publish-to-bcr@v2
        with:
          tag_name: ${{ inputs.tag_name }}
